### ISSUE TITLE
Make updateInterval user-settable

### ISSUE THREAD

**Issue by briansayles** [mizzao/meteor-timesync#10]
It would be beneficial to be able to set the timer to update more often than every second. Currently var updateInterval = 1000 and is not settable by the user. It would be nice if it would be able to be set via either TimeSync.updateInterval = xxx; or TimeSync.setUpdateInterval(xxx);

I am currently working on a countdown timer, and while I don't need the timer resolution to be any more precise than 1 second, it would be beneficial for the updateInterval to be less than 1 second. The reason for this is that individual machines will 'tick' at different fractions of a second based on when their timer was started (at page render in my case). So if one device renders at xx:xx:xx.250 and another renders at xx:xx:xx.750, their ticks will be 1/2 second off from each other. So when you watch a countdown on both machines, they're slightly out of sync, just because of when they tick. If I set the updateInterval for something in the area of 250 ms, the noticeable difference between the different devices essentially disappears. Going below that could make it literally disappear, but is not necessary in my case.

**Comment by mizzao** [comment]
You can now use `TimeSync.serverTime(null, XXX)` where `XXX` is an integer number of milliseconds specifying the rate that you'd like the variable to update at, default 1000.

**Comment by briansayles** [comment]
Excellent. Thank you. While I don't really need this functionality any more because I refactored my app a bit (per your recommendation which was good), I think it's a good feature for your package.
