### ISSUE TITLE
Is it possible to only use time-sync when needed?

### ISSUE THREAD

**Issue by elie222** [mizzao/meteor-timesync#13]
I only need time-sync on one page on my site, but time-sync is always running, trying to sync the time on the client and server. Is there a way for me to stop this and only use time-sync when I need it?

I know time-sync is doing its thing becauseI get the following error quite often. Even when I thought I wasn't using time-sync:
Clock discrepancy detected. Attempting re-sync.

**Comment by mizzao** [comment]
@elie222 you can now use `TimeSync.loggingEnabled = false` if you'd like to suppress those error messages in Kadira.

**Comment by elie222** [comment]
Thanks
