### ISSUE TITLE
removing the Clock discrepancy logging

### ISSUE THREAD

**Issue by piffie** [mizzao/meteor-timesync#21]
Hi,

I get about 10k of Log messages a day that it syncs the clock.
Please remove it as it totally blows up my console logging statistics...
line 127 
Meteor._debug("Clock discrepancy detected. Attempting re-sync.");

thanks

**Comment by mizzao** [comment]
You're always free to make your own fork of the package and remove that line :)

I don't see the huge problem with that line. But maybe we could create a setting where console logging can be enabled and disabled by the user, if you are using some sort of error-reporting system that is capturing the log messages.

**Comment by piffie** [comment]
But how can i overwrite the meteor-user-status to use mine than? Maybe if i
use the same name, just make the version number higher...
a setting would be perfect.
I use kadira.io and that captures it.

2015-01-26 18:54 GMT+01:00 Andrew Mao <notifications@github.com>:

**Comment by mizzao** [comment]
You can now use `TimeSync.loggingEnabled = false` to suppress log messages.

**Comment by Fen747** [comment]
Hi.

Though I'm using your packages and it works fine for me, I can't get rid of the logs. TimeSync is marked as undefined (before startup, in startup, on client and server).
