### ISSUE TITLE
TimeSync.serverTime is throwing NaN for android App built with Meteor

### ISSUE THREAD

**Issue by hemant4bluepi** [mizzao/meteor-timesync#27]

**Comment by mizzao** [comment]
What's `TimeSync.isSynced()` at the time you call this?

**Comment by hemant4bluepi** [comment]
True

**Comment by mizzao** [comment]
Can't help you too much without a reproduction. Can you make the simplest android app that exhibits this issue?

**Comment by hemant4bluepi** [comment]
Yeah but that would take time else you can just run android for any of your
meteor app that is using timesync.
In the meanwhile i will create a simple app using timesync

**Comment by KristerV** [comment]
wtf this would not be an issue if @mizzao would accept [this pull request](https://github.com/mizzao/meteor-timesync/pull/22). How annoying. Been waiting for some time now..

**Comment by mizzao** [comment]
Sorry, I am out of the country right now and will try to look at these as soon as I get back :)

**Comment by KristerV** [comment]
ok, thanks for letting us know.

**Comment by hemant4bluepi** [comment]
Thanks for the information

**Comment by jaskinn** [comment]
@mizzao Are you able to action the pull request that @KristerV is referring to now?

**Comment by mizzao** [comment]
Can you try the latest commit on Cordova?
