### ISSUE TITLE
TimeServer not syncing in Firefox.

### ISSUE THREAD

**Issue by faysal515** [mizzao/meteor-timesync#28]
TimeSync.resync();

                if(TimeSync.isSynced()){
                    console.log("current Time from if >>> "+ TimeSync.serverTime()/1000);
                }

The above is my client-side code . Chrome console works fine. But Firefox does nothing instead of re syncing  it forcefully.

**Comment by mizzao** [comment]
Resync happens automatically as the app is loading, and it is not synchronous. There is no need to call it.

It seems like your `isSynced` is just getting called before the initial sync happens.

**Comment by faysal515** [comment]
sorry for the delayed response. fixed the issue by syncing the time in `Meteor.startup`

**Comment by mizzao** [comment]
@faysal515 there should be no need for you to call `TimeSync.resync()` at all in most cases. It is called upon startup automatically.

**Comment by faysal515** [comment]
thank you for the response. but Firefox threw me sometimes not a number error, thus had to make this up.
