### ISSUE TITLE
Not working on secure site?

### ISSUE THREAD

**Issue by crsssl** [mizzao/meteor-timesync#29]
TimeSync.serverTime() just returns undefined. Other methods, too.
TimeSync.resync() returns:
```
Mixed Content: The page at 'https://mysite.com/reports' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://mysite.com/_timesync'. This request has been blocked; the content must be served over HTTPS.
```
These browser-based mixed content issues are SO annoying. Any way to get around this? Or do you have a fix?

I'm on Node v0.10.36, btw. Thanks.

**Comment by crsssl** [comment]
Jumped the gun. It just needed the ROOT_URL environment variable set. Never mind.

**Comment by mizzao** [comment]
Side-effect caused by ad4ef5cea70e7508e3a79d970498e1476b9e850a in the process of fixing #22, but agreed that it can be fixed by manually setting `ROOT_URL`.

The only reason we needed to this rather than just going with `/_timesync` is that the Cordova syntax is different.

**Comment by mizzao** [comment]
I'm curious why it ended up trying to grab a `http://` URL with the same site. That seems very strange.

**Comment by crsssl** [comment]
It's the default return from ```Meteor.absoluteUrl("_timesync")```. See the client-side ```updateOffset``` function.
