### ISSUE TITLE
Origin domain mix up

### ISSUE THREAD

**Issue by hluz** [mizzao/meteor-timesync#30]
Started to get messages like this in the browser console:

XMLHttpRequest cannot load http://my.internal.domain/_timesync. Origin http://my.domain.com is not allowed by Access-Control-Allow-Origin.

Any hints of what to do to fix it?

**Comment by mizzao** [comment]
Caused by 2ccdba4613a1866783e10c02c1e13bfdb222ec14 trying to fix this for Cordova. I will refactor this again for a more robust solution.

By the way, are you setting `ROOT_URL` in the deployment of your app?

**Comment by mizzao** [comment]
Hey, can you try v0.3.3 in your app?

**Comment by hluz** [comment]
Thanks Andrew. Yes, I'm setting the ROOT_URL to http://my.internal.domain... Should I be using http://my.domain.com instead? (fyi, my.internal.domain is not resolvable externally, just behind the co firewalls).

I will try the new version in the next prod drop (don't have the issue in the Test environment since only one domain name is in play...).

**Comment by mizzao** [comment]
`ROOT_URL` is supposed to be the URL that your users are accessing your app by. So unless you're using it both internally and externally, it would be the external address of the reverse proxy.

In any case, I agree that this is a somewhat silly design choice by Meteor (to support accessing an app only by one URL) so I avoided using the `Meteor.absoluteUrl` function unless absolutely necessary (for Cordova).

**Comment by hluz** [comment]
Yeah. Agree. I need also the internal one because most people internally rely on the DHCP search domain suffix for resolution (using host part without the domain)...

**Comment by jaredthirsk** [comment]
I am hosting  the ROOT_URL at a sub-path, example:  https://mydomain.com/timer.  I am getting 404 on /_timesync.  What should I do?

**Comment by mizzao** [comment]
Not sure. The problem with using `ROOT_URL` is that in development you can't access your app from both `127.0.0.1` and whatever your local network address is. So we should think of a solution to this.

How do you even host a meteor app at a sub-path?

**Comment by jaredthirsk** [comment]
I am hosting on my own box.  In development, I don't change ROOT_URL.  In my deployment, I set ROOT_URL to http://domain.com/timer/ and nginx is like this:

   location ^~ /timer {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade; # allow websockets
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header X-Forwarded-For $remote_addr; # preserve client IP

        # this setting allows the browser to cache the application in a way compatible with Meteor
        # on every applicaiton update the name of CSS and JS file is different, so they can be cache infinitely (here: 30 days)
        # the root path (/) MUST NOT be cached
        if ($uri != '/timer') {
            expires 30d;
        }
    }

**Comment by jaredthirsk** [comment]
I think I got it working for my purposes.  I eliminate the Cordova check and always use Meteor.absoluteUrl.  On the server, I had to do some string manipulation to get the application's base path which gets used by the connect api.

https://github.com/jaredthirsk/meteor-timesync/commit/ce6eea1f83953a93f4d240aa6ad36cbb49b1725b

**Comment by jaredthirsk** [comment]
(In development, I set ROOT_URL when accessing from another box.)

What's the solution?  Your solution doesn't work for subdomains so it doesn't seem right.  Should the meteor guys create another method like absoluteUrl that just has the path, that everyone should be using, and give paths to clients?   Should they replace the ROOT_URL concept with a LISTEN_IP?
