### ISSUE TITLE
HTTPS Server Content Policy Problem

### ISSUE THREAD

**Issue by fuatsengul** [mizzao/meteor-timesync#31]
I see a strange error in the production app.
I think timesync is confusing on HTTPS protocol, maybe there's a manual setting for host address? 

Here's one of error messages:
```
Mixed Content: The page at 'https://example.com/admin' was loaded over HTTPS, 
but requested an insecure XMLHttpRequest endpoint 'http://example.com/_timesync'. 
This request has been blocked; the content must be served over HTTPS.
```

**Comment by mizzao** [comment]
Are you using v0.3.3 of the package?

**Comment by fuatsengul** [comment]
I use user-status@0.6.5, which have dependency to timesync@0.3.2

**Comment by mizzao** [comment]
Just try manually adding `mizzao:timesync@0.3.3` for now.

**Comment by fuatsengul** [comment]
Thanks :)
I think there's nothing wrong right now.
