### ISSUE TITLE
ROOT_URL is ignored

### ISSUE THREAD

**Issue by peterkuiper** [mizzao/meteor-timesync#36]
When running a meteor app from within a subdirectory and specifying ROOT_URL (ie ROOT_URL=http://domain.com/app1), /_timesync is being used instead of /app1/_timesync. I can see in the source that it is hardcoded to /_timesync. It would be nice if ROOT_URL can be taken into account for this.

**Comment by mizzao** [comment]
Hi @peterkuiper, is this the same as #40 - that is, resolvable using `ROOT_URL_PATH_PREFIX`?

**Comment by peterkuiper** [comment]
Yes, it is. Thanks for merging!
