### ISSUE TITLE
DDP Package dependency not declared

### ISSUE THREAD

**Issue by afuggini** [mizzao/meteor-timesync#38]
Hi @mizzao,

Just had some issues on my app and I realized this package depends on the native `ddp` package but the dependency is not declared. Shouldn't it be?

I'll send a pull request.

Thanks.

**Comment by mizzao** [comment]
Are you using Meteor 1.3 by any chance?

**Comment by afuggini** [comment]
@mizzao No, I'm using 1.2.1 and loading the package from the package level, not the app level.

**Comment by mizzao** [comment]
I'm just looking at this and I'm not sure what you mean - there is no dependency on `DDP` or `DDPServer` anywhere in the package.

**Comment by mizzao** [comment]
I think you were referring to #42 (`Deps`, not `DDP`), and this should be fixed now.
