### ISSUE TITLE
Adjust CORS headers for Cordova changes in Meteor 1.3

### ISSUE THREAD

**Issue by martijnwalraven** [mizzao/meteor-timesync#41]
Because Meteor 1.3 serves Cordova apps from `localhost:<port>` instead of `meteor.local`, the CORS header set [here](https://github.com/mizzao/meteor-timesync/blob/master/timesync-server.js#L17) will need to be changed.

See the changes made in CollectionFS for more details:
https://github.com/CollectionFS/Meteor-http-methods/commit/7ebfe12bda81d3335c1ea75a40af32fd8817f815

**Comment by mizzao** [comment]
I think this was brought up in #37; I've been traveling lately and haven't had a chance to look at it yet. Will do so soon.
