### ISSUE TITLE
Deps is not defined

### ISSUE THREAD

**Issue by selaias** [mizzao/meteor-timesync#42]
after upgrading to 0.4.0 i get an exception

ReferenceError: Deps is not defined
 (STDERR)     at Package (timesync-client.js:20:18)

line 20 should be : new Tracker.Dependency() i guess

**Comment by mizzao** [comment]
Thanks for the report. What version of Meteor are you using?

**Comment by selaias** [comment]
I'm running METEOR@1.2.1 and didn't have problems before with the package.

**Comment by kafechew** [comment]
Same issue as selaias here (Meteor 1.2.1).

**Comment by mizzao** [comment]
I just noticed today this seems to happen on Windows, but not Linux. Any chance you guys are using Windows?

**Comment by mizzao** [comment]
It seems like there may have been an Atmosphere bug when I published this, causing package code to show up on both the server and the client. Can you guys checkout the latest version directly into `packages/` and see if it causes the same issue?

**Comment by kafechew** [comment]
Yea~ seems like "Deps" error as you predicted:

/Users/kafechew/.meteor/packages/meteor-tool/.1.1.10.1cc1oiz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160628-19:14:09.921(8)? (STDERR) 						throw(ex);
W20160628-19:14:09.921(8)? (STDERR) 						      ^
W20160628-19:14:09.934(8)? (STDERR) ReferenceError: Deps is not defined
W20160628-19:14:09.935(8)? (STDERR)     at Package (timesync-client.js:20:18)
W20160628-19:14:09.935(8)? (STDERR)     at /Users/kafechew/meteor/sensq2/sensq2/.meteor/local/build/programs/server/packages/mizzao_timesync.js:242:4
W20160628-19:14:09.935(8)? (STDERR)     at /Users/kafechew/meteor/.meteor/local/build/programs/server/packages/mizzao_timesync.js:249:3
W20160628-19:14:09.935(8)? (STDERR)     at /Users/kafechew/meteor/.meteor/local/build/programs/server/boot.js:242:10
W20160628-19:14:09.935(8)? (STDERR)     at Array.forEach (native)
W20160628-19:14:09.935(8)? (STDERR)     at Function._.each._.forEach (/Users/kafechew/.meteor/packages/meteor-tool/.1.1.10.1cc1oiz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160628-19:14:09.935(8)? (STDERR)     at /Users/kafechew/meteor/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
 
But, still no idea how to fix it.
Thanks for your help :-)

**Comment by mizzao** [comment]
@kafechew: can you try checking out timesync locally and seeing if you still have the error? If not, maybe it was just a one-time issue and I will just bump the package on atmosphere.

**Comment by roelvan** [comment]
Same here, now I am using @=0.3.4 which removes this problem.

**Comment by ConnorSheremeta** [comment]
@mizzao Not getting this issue in 0.4.0, but getting it in 0.3.4 (Meteor 1.2.1). Checking it out locally resolved it. Can anyone else confirm?

**Comment by mizzao** [comment]
Okay, it seems like we just need to bump the package version. Really strange why this happens - there is clearly a dependency on `Tracker` in 0.4.0

**Comment by mizzao** [comment]
@maxnowack has pushed out 0.5.0 of this package and I think it should have resolved this (strange) issue. Closing for now; please comment if you see the same issue in this version.

**Comment by mizzao** [comment]
I just verified that on Meteor 1.2.1, both 0.4.0 and 0.5.0 of this package have issues—somehow, the server tries to load client code improperly, even though it goes away if the package is checked out locally.

Meteor 1.3.5.1 does not have this problem. So, I recommend trying to upgrade to that version instead. There aren't too many changes.
