### ISSUE TITLE
Take an action when not in Sync

### ISSUE THREAD

**Issue by AndyNormore** [mizzao/meteor-timesync#47]
Hi there, I'm running a video game that is using this library. Www.StarCommanderOnline.com

I would like to perform an action like window.reload(); after a user dysncronzied, there is a lot of redrawing that has to occur when this happens, so I'd like to just reload them.

How does one force a function to run when not in sync?

**Comment by mizzao** [comment]
Use the reactive `TimeSync.isSynced()` function.

**Comment by AndyNormore** [comment]
So this?

if(!TimeSync.isSynced()){
 alert("Oh no, we appear to be mis-communicated from the server!");
}

Thanks for your reply.

**Comment by AndyNormore** [comment]
I can confirm that my script above works perfectly! I am now using this function to determine if the user has gone afk, lost connection, and am re-running subscriptions with the help of this function!

Thanks @mizzao
